// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jecwaulaaxwdqrchanzy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImplY3dhdWxhYXh3ZHFyY2hhbnp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyODkwNDIsImV4cCI6MjA3MTg2NTA0Mn0.PtdZ5qxLrY9PtU_HSBfLpMBCdHzLgWt5QXjEmb3NFsU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});